import React from "react";
import { FolderTree, FileCode, CheckCircle2, Terminal, Play, GitBranch, Cpu } from "lucide-react";

export function ProductPreview() {
  return (
    <section id="preview" className="relative py-20 border-t border-zinc-800/40">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center mb-12 space-y-2">
          <p className="text-xs font-mono uppercase tracking-widest text-zinc-500">Workspace</p>
          <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-zinc-100">
            Intelligent by design
          </h2>
          <p className="text-xs sm:text-sm text-zinc-400">
            A unified environment where AI writes, tests, and validates code alongside you.
          </p>
        </div>

        {/* Mock IDE Window Container */}
        <div className="relative rounded-2xl border border-zinc-800/90 bg-zinc-950/80 shadow-2xl overflow-hidden backdrop-blur-xl">
          {/* Top Window Bar */}
          <div className="flex h-10 items-center justify-between border-b border-zinc-800/80 bg-zinc-900/60 px-4">
            <div className="flex items-center gap-2">
              <div className="size-2.5 rounded-full bg-zinc-700/80" />
              <div className="size-2.5 rounded-full bg-zinc-700/80" />
              <div className="size-2.5 rounded-full bg-zinc-700/80" />
              <span className="ml-3 font-mono text-[11px] text-zinc-400 hidden sm:inline">
                codra-workspace — main
              </span>
            </div>

            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1.5 rounded-md border border-zinc-800 bg-zinc-900/90 px-2 py-0.5 text-[11px] font-mono text-zinc-400">
                <GitBranch className="size-3 text-zinc-400" />
                <span>feat/smart-codegen</span>
              </div>
              <div className="flex items-center gap-1 rounded-md bg-zinc-800/80 px-2 py-0.5 text-[11px] font-mono text-emerald-400">
                <Play className="size-2.5 fill-current" />
                <span>Live</span>
              </div>
            </div>
          </div>

          {/* IDE Panes Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-12 min-h-[380px] divide-y lg:divide-y-0 lg:divide-x divide-zinc-800/80 text-xs font-mono">
            {/* Left: File Explorer (3 cols) */}
            <div className="hidden sm:block lg:col-span-3 bg-zinc-950/40 p-3 space-y-3">
              <div className="flex items-center gap-1.5 text-zinc-400 font-semibold uppercase tracking-wider text-[10px]">
                <FolderTree className="size-3.5" />
                <span>Explorer</span>
              </div>

              <div className="space-y-1 text-zinc-400">
                <div className="text-zinc-500 font-medium pl-1">▼ apps/web</div>
                <div className="pl-4 py-1 text-zinc-300 bg-zinc-900/60 rounded flex items-center gap-1.5 border-l-2 border-zinc-400">
                  <FileCode className="size-3 text-zinc-300" />
                  <span>app/api/auth.ts</span>
                </div>
                <div className="pl-4 py-1 text-zinc-400 hover:text-zinc-200 flex items-center gap-1.5">
                  <FileCode className="size-3 text-zinc-500" />
                  <span>components/canvas.tsx</span>
                </div>
                <div className="pl-4 py-1 text-zinc-400 hover:text-zinc-200 flex items-center gap-1.5">
                  <FileCode className="size-3 text-zinc-500" />
                  <span>app/layout.tsx</span>
                </div>

                <div className="text-zinc-500 font-medium pl-1 pt-2">▼ packages/db</div>
                <div className="pl-4 py-1 text-zinc-400 hover:text-zinc-200 flex items-center gap-1.5">
                  <FileCode className="size-3 text-zinc-500" />
                  <span>prisma/schema.prisma</span>
                </div>
              </div>
            </div>

            {/* Center: Code Editor (6 cols) */}
            <div className="lg:col-span-6 bg-[#090a0f] p-4 sm:p-5 overflow-x-auto space-y-1.5 text-zinc-300 leading-relaxed font-mono">
              <div className="text-zinc-500">// Generated by Codra Agent</div>
              <div>
                <span className="text-purple-400">import</span> &#123; prismaClient &#125;{" "}
                <span className="text-purple-400">from</span>{" "}
                <span className="text-emerald-300">"@codra/db"</span>;
              </div>
              <div>
                <span className="text-purple-400">import</span> &#123; z &#125;{" "}
                <span className="text-purple-400">from</span>{" "}
                <span className="text-emerald-300">"zod"</span>;
              </div>
              <div className="py-1" />
              <div>
                <span className="text-blue-400">export async function</span>{" "}
                <span className="text-yellow-300">synthesizeModule</span>(
                <span className="text-zinc-300">payload: z.infer&lt;typeof Schema&gt;</span>
                ) &#123;
              </div>
              <div className="pl-4 text-zinc-400">
                <span className="text-blue-400">const</span> workspace ={" "}
                <span className="text-purple-400">await</span> prismaClient.workspace.
                <span className="text-yellow-300">create</span>(&#123;
              </div>
              <div className="pl-8 text-zinc-300">
                data: &#123; name: payload.title, status:{" "}
                <span className="text-emerald-300">"ACTIVE"</span> &#125;,
              </div>
              <div className="pl-4">&#125;);</div>
              <div className="pl-4 text-zinc-400">
                <span className="text-purple-400">return</span> &#123; success:{" "}
                <span className="text-orange-400">true</span>, workspace &#125;;
              </div>
              <div>&#125;</div>
            </div>

            {/* Right: AI Execution Stream (3 cols) */}
            <div className="lg:col-span-3 bg-zinc-950/60 p-4 space-y-4">
              <div className="flex items-center gap-1.5 text-zinc-400 font-semibold uppercase tracking-wider text-[10px]">
                <Cpu className="size-3.5 text-zinc-400" />
                <span>Agent Activity</span>
              </div>

              <div className="space-y-2.5 text-[11px]">
                <div className="flex items-start gap-2 text-zinc-300 bg-zinc-900/60 p-2 rounded-lg border border-zinc-800/80">
                  <CheckCircle2 className="size-3.5 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <div className="font-medium text-zinc-200">Schema generated</div>
                    <div className="text-zinc-500 text-[10px]">Prisma migration ready</div>
                  </div>
                </div>

                <div className="flex items-start gap-2 text-zinc-300 bg-zinc-900/60 p-2 rounded-lg border border-zinc-800/80">
                  <CheckCircle2 className="size-3.5 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <div className="font-medium text-zinc-200">API routes wired</div>
                    <div className="text-zinc-500 text-[10px]">End-to-end type safety</div>
                  </div>
                </div>

                <div className="flex items-start gap-2 text-zinc-300 bg-zinc-900/40 p-2 rounded-lg border border-zinc-800/40">
                  <Terminal className="size-3.5 text-blue-400 shrink-0 mt-0.5 animate-pulse" />
                  <div>
                    <div className="font-medium text-zinc-200">Running type checks</div>
                    <div className="text-zinc-500 text-[10px]">0 warnings found</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
