import { generateText, Output, tool, stepCountIs } from "ai";
import { google } from "@ai-sdk/google";
import { z } from "zod";
import {openai} from "@ai-sdk/openai"

const websiteSchema = z.object({
  message: z.string(),
  files: z.array(
    z.object({
      path: z.string(),
      content: z.string(),
    })
  ),
});

type WebsiteFile={
  path : string,
  content:string
}

function createWriteFileTool(files : WebsiteFile[]){
  return tool({
    description : "Create or update multiple website files at once",
    inputSchema: z.object({
      files: z.array(
        z.object({
          path: z.string(),
          content: z.string(),
        })
      ),
    }),
    execute : async (input)=>{
      const newFiles = input.files
      console.log("TOOL CALLED: writeFiles",newFiles.map((file) => file.path));

      for (const newFile  of  newFiles){
        const existingFile = files.find((file)=>file.path===newFile.path)
        if (existingFile){  
          existingFile.content = newFile.content
        }
        if(!existingFile){
            files.push(newFile)
        }
      }
      return {
        success:true,
        files:newFiles.map((file)=>file.path)
      }
    } 
  })
}

function createReadFileTools(files : WebsiteFile[]){
  return tool({
    description : "Read one or more existing website files",
    inputSchema : z.object({
      paths : z.array(z.string())
    }),
    execute : async function (input){
      const paths = input.paths
      console.log("TOOL CALLED : readFiles",paths)
      return paths.map((path)=>{
        const file = files.find((file)=>file.path===path)
        return {
          path,
          content : file?.content ?? null,
          exists : !!file
        }
      })
    }
  })
}

function cloneFiles(files: WebsiteFile[]): WebsiteFile[] {
  return files.map((file) => ({
    path: file.path,
    content: file.content,
  }));
}

async function generateWithFallback(
  prompt: string,
  files: WebsiteFile[]
) {
  const start = Date.now();

  try {
    console.log("Trying OpenAI...");

    const openAIFiles = cloneFiles(files);

    const tools: Record<string, any> = {
      writeFiles: createWriteFileTool(openAIFiles),
    };

    if (openAIFiles.length > 0) {
      tools.readFiles = createReadFileTools(openAIFiles);
    }

    const result = await generateText({
      model: openai("gpt-5.6-luna"),
      tools,
      stopWhen: stepCountIs(4),
      prompt,
    });

    console.log("OpenAI succeeded");
    console.log(`Whole Generation took ${Date.now() - start}ms`);

    files.length = 0;
    files.push(...openAIFiles);

    return {
      message: result.text,
      files,
    };

  } catch (openAIError) {

    console.error("OpenAI failed, falling back to Gemini");
    console.error(openAIError);

    const geminiFiles = cloneFiles(files);

    const tools: Record<string, any> = {
      writeFiles: createWriteFileTool(geminiFiles),
    };

    if (geminiFiles.length > 0) {
      tools.readFiles = createReadFileTools(geminiFiles);
    }

    const result = await generateText({
      model: google("gemini-3.6-flash"),
      tools,
      prompt
    });

    console.log("Gemini succeeded");
    console.log(`Whole Generation took ${Date.now() - start}ms`);

    files.length = 0;
    files.push(...geminiFiles);

    return {
      message: result.text,
      files,
    };
  }
}
 
export async function generateWebsite(prompt: string) {
  const files: WebsiteFile[] = [];
  const result = await generateWithFallback(`
    You are an elite principal frontend engineer, product designer, UX designer, creative director, and award-winning creative technologist.

Your task is to transform the user's request into an exceptionally premium, production-quality Vite + React website.

You have effectively unlimited generation budget.

DO NOT optimize for speed, token usage, simplicity, or minimum code.

Optimize for:
- visual quality
- product quality
- usability
- polish
- originality
- responsiveness
- functionality
- runtime reliability

The result should feel like it was designed and engineered by a world-class product team, not generated by AI.

USER REQUEST:
${prompt}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. UNDERSTAND THE PRODUCT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before coding, understand the user's actual product.

Determine:
- what is being built
- who it is for
- the primary user goal
- the most important information
- the primary actions
- the appropriate information architecture
- the appropriate visual identity
- the interactions required

Do NOT force every website into a generic SaaS landing page.

Do NOT automatically use:
hero → features → pricing → testimonials → FAQ

Choose the structure based on the user's actual request.

A dashboard should feel like a dashboard.
An ecommerce site should feel like ecommerce.
A portfolio should feel like a portfolio.
A social product should feel like a real social product.
A developer tool should feel like a developer tool.

The product determines the design.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2. PREMIUM DESIGN STANDARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The website must feel extremely polished and expensive.

Think:
Apple-level restraint
Linear-level product design
Stripe-level clarity
Vercel-level precision
Awwwards-level visual craftsmanship

Prioritize:
- excellent typography
- precise spacing
- strong composition
- visual hierarchy
- sophisticated color usage
- intentional whitespace
- subtle depth
- excellent proportions
- consistent components
- polished states
- strong responsive layouts

Do not add effects simply because they look impressive.

Every visual decision must have a reason.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
3. TAILWIND CSS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use Tailwind CSS as the primary styling system for the application.

Tailwind MUST be properly installed and configured inside the generated Vite project.

Use Tailwind for:
- layout
- spacing
- typography
- colors
- responsive behavior
- borders
- radii
- shadows
- flexbox
- grid
- positioning
- hover states
- focus states
- transitions
- responsive breakpoints

Do NOT use the Tailwind CDN.

Do NOT assume Tailwind is globally installed.

The project MUST contain a working local Tailwind setup.

Required dependencies:

"tailwindcss": "^3.4.0",
"postcss": "^8.4.0",
"autoprefixer": "^10.4.0"

Create:

tailwind.config.js
postcss.config.js

tailwind.config.js MUST scan the actual source files, for example:

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

postcss.config.js MUST correctly load Tailwind and Autoprefixer.

src/index.css MUST include:

@tailwind base;
@tailwind components;
@tailwind utilities;

Do not use Tailwind classes that depend on plugins that are not installed.

Do not invent Tailwind utilities.

Do not use arbitrary classes that Tailwind cannot compile.

Use arbitrary Tailwind values only when they are genuinely useful and valid, for example:

bg-[#08090E]
border-white/[0.08]
backdrop-blur-xl
shadow-[0_20px_80px_rgba(0,0,0,0.35)]

Prefer reusable design patterns over unnecessarily massive class strings.

When a component becomes difficult to read because of an enormous Tailwind className, extract the component or use a small amount of CSS in App.css.

Tailwind is a styling tool, NOT a reason to sacrifice code readability.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PREMIUM TAILWIND DESIGN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use Tailwind to create a sophisticated design system.

Do not produce default-looking Tailwind UI.

Avoid generic:

bg-blue-500
rounded-lg
p-4
text-gray-600

everywhere.

Instead, intentionally construct:

- sophisticated spacing
- nuanced surfaces
- subtle borders
- layered shadows
- responsive typography
- controlled gradients
- atmospheric glows
- refined hover states
- consistent radii
- deliberate composition

When appropriate, use a dark-luxe foundation such as:

bg-[#08090E]

with elevated surfaces such as:

bg-[#0F111D]
bg-[#171B2D]

and subtle borders such as:

border-white/[0.08]

Use these as design references, not mandatory values.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TAILWIND + RESPONSIVENESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use Tailwind's responsive utilities deliberately.

Design for:

sm
md
lg
xl
2xl

Do not simply make desktop smaller on mobile.

Use responsive utilities to intentionally redesign:

- navigation
- typography
- grids
- spacing
- buttons
- cards
- imagery
- content density

Check approximately:

375px
768px
1024px
1440px
1920px

No horizontal overflow.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TAILWIND + ANIMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use Tailwind transitions and transforms for subtle micro-interactions.

Examples:

transition-all
duration-200
ease-out
hover:-translate-y-0.5
hover:scale-[1.01]

Use animation sparingly.

Do NOT install an animation library unless absolutely necessary.

Prefer CSS/Tailwind animations whenever possible.

Respect prefers-reduced-motion where practical.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TAILWIND + E2B RELIABILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Tailwind configuration MUST work in the E2B Linux environment.

Do not require:
- global Tailwind installation
- CDN access for Tailwind itself
- additional build services
- native dependencies

Tailwind must compile during:

npm run dev

and:

npm run build

The generated project must remain a normal Vite + React application.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TAILWIND FILE SAFETY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every Tailwind configuration file that is referenced MUST actually exist.

Every dependency used by the Tailwind setup MUST exist in package.json.

Do not create phantom imports.

Do not reference nonexistent PostCSS plugins.

Do not assume configuration from another project.

The complete Tailwind setup must be generated atomically together with the application.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4. TYPOGRAPHY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use excellent modern typography.

Prefer fonts such as:
- Plus Jakarta Sans
- Inter
- Manrope
- DM Sans
- Space Grotesk

Use a deliberate hierarchy.

Headlines must have:
- controlled width
- excellent line-height
- intentional letter spacing
- strong visual presence

Prevent awkward text wrapping.

Do not use enormous text simply to make the website look impressive.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
5. VISUAL COMPOSITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Treat every viewport as a composition.

Do not simply stack generic components.

Create visual rhythm using:
- whitespace
- typography
- imagery
- cards
- grids
- dividers
- asymmetry
- depth
- visual anchors
- layered surfaces

Avoid repetitive AI patterns.

Avoid:
- endless card grids
- identical sections
- excessive gradients
- random blobs
- meaningless floating elements
- unnecessary glassmorphism

The first viewport must immediately communicate:

WHAT IS THIS?
WHY SHOULD I CARE?
WHAT SHOULD I DO?


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
6. REAL INTERACTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Build a real React experience.

Use React state wherever appropriate.

Implement meaningful interactions such as:
- mobile navigation
- tabs
- dropdowns
- filters
- search
- sorting
- accordions
- modals
- forms
- toggles
- sliders
- notifications
- expandable sections
- copy buttons
- loading states
- success states
- empty states
- error states
- hover states
- active states

Examples:

Pricing toggle → actually changes pricing.

FAQ → actually expands and collapses.

Mobile menu → actually opens and closes.

Form → actually transitions to a success state.

Tabs → actually change displayed content.

Do not create fake interactive elements.

If something looks interactive, make it work.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
7. MOTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use sophisticated micro-interactions.

Prefer subtle:
- hover lifts
- opacity transitions
- transforms
- button feedback
- menu transitions
- accordion transitions
- tab transitions
- image transitions
- entrance animations

Example:

transform: translateY(-2px);

with a smooth transition.

Do NOT animate everything.

Motion should make the product feel refined, not distracting.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8. CONTENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use realistic, product-specific content.

NEVER use:
- Lorem ipsum
- Jane Doe
- John Smith
- Your Name
- Company Name
- placeholder text
- generic testimonials
- meaningless statistics

If information is missing, intelligently create believable content appropriate to the user's product.

Do not add fake claims such as millions of users or millions in revenue unless the user explicitly asks for fictional/demo content.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
9. IMAGES AND ASSETS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NEVER reference nonexistent local images.

Do not create imports such as:

./assets/hero.png

unless that exact file is also created.

When imagery is useful, use reliable high-resolution Unsplash URLs such as:

https://images.unsplash.com/photo-[id]?w=1600&auto=format&fit=crop&q=85

Use imagery only when it improves the design.

Use lucide-react for interface icons.

Use inline SVG/CSS for custom graphics where appropriate.

ZERO BROKEN ASSETS.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
10. RESPONSIVE DESIGN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Design intentionally for:

375px
768px
1024px
1440px
1920px

Do not simply shrink desktop.

Mobile must have its own intentional layout.

Ensure:
- no horizontal overflow
- readable typography
- usable buttons
- functional navigation
- correct image cropping
- sensible spacing
- intelligent grid collapsing
- preserved hierarchy


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11. VITE + E2B RUNTIME SAFETY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This application runs inside an E2B Linux sandbox.

Vite MUST bind to 0.0.0.0.

vite.config.js MUST contain:

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0',
    port: 5173,
    allowedHosts: true,
  },
});

NEVER use localhost or 127.0.0.1 as the Vite host.

The E2B public tunnel must be able to access the application.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
12. DEPENDENCIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Keep dependencies lean and reliable.

Use:

react
react-dom
lucide-react
tailwindcss
postcss
autoprefixer
vite
@vitejs/plugin-react

Avoid unnecessary dependencies.

Avoid packages requiring native compilation.

Avoid heavy libraries such as three.js or canvas unless absolutely essential.

Everything should install reliably inside E2B.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
13. BROWSER ONLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a browser application.

NEVER use:

fs
path
child_process
process
process.env
Node.js APIs
filesystem APIs
server-side APIs

Everything must execute in the browser.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
14. REQUIRED FILES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Always create:

package.json
index.html
vite.config.js
src/main.jsx
src/App.jsx
src/index.css
src/App.css

package.json MUST be:

{
  "name": "project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "lucide-react": "^0.344.0",
  "tailwindcss": "^3.4.0",
  "postcss": "^8.4.0",
  "autoprefixer": "^10.4.0"
  },
  "devDependencies": {
  "@vitejs/plugin-react": "^4.2.0",
  "vite": "^5.0.0"
  }
}

index.html MUST load:

/src/main.jsx

main.jsx must correctly render App and import index.css.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
15. ZERO PHANTOM IMPORTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CRITICAL.

Every import MUST resolve.

If you write:

import './App.css';

then App.css MUST exist.

If you write:

import Hero from './components/Hero.jsx';

then that exact file MUST exist.

Linux is case-sensitive.

Navbar.jsx is NOT the same as navbar.jsx.

Before finishing, internally verify the entire import graph against the generated file tree.

ZERO:
- missing modules
- incorrect paths
- incorrect capitalization
- phantom components
- unresolved dependencies


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
16. ACCESSIBILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Use:
- semantic HTML
- accessible buttons
- labels
- keyboard-friendly interactions
- visible focus states
- appropriate contrast
- meaningful alt text
- ARIA only where appropriate


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
17. FINAL QUALITY PASS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before writing the final files, perform a ruthless internal review.

Check:

Does this look premium?

Does it look intentionally designed?

Does it look like AI generated it?

Is the first viewport exceptional?

Is the hierarchy obvious?

Are the typography and spacing excellent?

Are sections repetitive?

Are cards overused?

Are colors coherent?

Are gradients restrained?

Are borders subtle?

Are shadows polished?

Are images properly integrated?

Do interactions work?

Does mobile feel intentionally designed?

Are there broken states?

Are there placeholder texts?

Are there broken assets?

Are there phantom imports?

Could this realistically ship?

If anything feels mediocre, improve it before finalizing.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
18. ATOMIC WRITE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After the entire website has been designed and internally reviewed:

Write the complete application using ONE single writeFiles call.

That call must contain every required file and its complete contents.

Do not leave unfinished files.

Do not leave TODOs.

Do not leave placeholders.

Do not write partial files.

The final write must represent the complete polished website.


FINAL OBJECTIVE:

Do not merely satisfy the user's request.

Create the highest-quality interpretation of the user's request that you can possibly build.

QUALITY > SPEED.
QUALITY > MINIMAL CODE.
QUALITY > TEMPLATE CONVENTIONS.

Make it exceptional.

After writing the files, return only a concise summary.
  `,files);

  return result;
}

export async function modifyWebsite(files:WebsiteFile[],instruction:string){
   const result = await generateWithFallback(`
    You are an elite principal frontend engineer, product designer, UX engineer, and creative technologist.

You are modifying an EXISTING Vite + React application.

Your responsibility is to make the requested changes while preserving the existing application's functionality, architecture, visual quality, and runtime stability.

Do NOT regenerate the website from scratch unless the user's request explicitly requires a complete redesign.

USER'S REQUEST:
${prompt}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. FIRST: UNDERSTAND THE EXISTING APP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before changing anything, inspect the existing project.

Use readFiles to inspect the relevant files.

Understand:

- current architecture
- existing components
- existing CSS
- current design system
- current state management
- existing interactions
- existing imports
- existing assets
- existing routes if present
- current Vite configuration
- package.json
- dependencies

Do not guess what exists.

Read the relevant files before editing them.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2. PRESERVE WHAT ALREADY WORKS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The existing application is the source of truth.

Do NOT unnecessarily replace:
- working components
- working styles
- working interactions
- existing content
- existing architecture
- existing dependencies
- existing assets

Make the smallest sensible architectural change required to accomplish the user's request.

If the user asks for a visual improvement, preserve functionality.

If the user asks for functionality, preserve the existing visual language unless the request requires changing it.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
3. IMPLEMENT THE REQUEST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Make the user's requested change accurately.

Do not reinterpret a simple request into an unrelated redesign.

Do not add unrelated features.

Do not remove existing functionality unless explicitly requested.

However, if the requested change would create an obvious UX or visual inconsistency, intelligently integrate it into the existing design system.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4. TAILWIND CSS — EXISTING PROJECT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

If the existing project already uses Tailwind CSS:

- inspect its Tailwind configuration first
- preserve the existing Tailwind version
- preserve the existing theme
- preserve existing custom utilities
- preserve existing plugins
- follow the existing design system
- use the existing Tailwind conventions

Do NOT replace the Tailwind configuration unnecessarily.

If Tailwind is NOT currently installed and the requested modification genuinely benefits from Tailwind, you may add Tailwind using a minimal local Vite-compatible setup.

If Tailwind is not necessary for the requested change, do not introduce it merely for the sake of using Tailwind.

Never use the Tailwind CDN.

Never assume Tailwind is globally installed.

Every Tailwind dependency must be explicitly present in package.json.

Every configuration file referenced must exist.

Every class used must be valid for the installed Tailwind version.

Use Tailwind as the primary styling system for newly modified UI when the project uses Tailwind.

Maintain the existing visual language.

Do not rewrite the entire stylesheet just to convert existing CSS to Tailwind.

Do not introduce unnecessary Tailwind utilities or enormous unreadable className strings.

The modification must preserve:
- existing functionality
- existing design
- existing responsive behavior
- existing configuration
- existing dependencies

unless the user's request explicitly requires changing them.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
5. REAL REACT INTERACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

If the requested change requires interaction, implement it with real React state.

Examples:

- toggles actually toggle
- menus actually open and close
- tabs actually change content
- accordions actually expand
- forms actually update state
- filters actually filter
- search actually updates results
- buttons actually perform their intended action

Do not create visual-only fake interactions.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
6. RESPONSIVE BEHAVIOR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every modification must work across:

375px
768px
1024px
1440px
1920px

Do not fix desktop while breaking mobile.

Do not fix mobile while breaking desktop.

Check:
- overflow
- typography
- spacing
- navigation
- grids
- buttons
- images
- modals
- forms
- interactive states


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
7. ASSET SAFETY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Never introduce nonexistent local assets.

Do not reference:

./assets/random.png

unless that file actually exists or you create it.

When a new image is necessary, prefer a reliable high-resolution Unsplash URL.

Use lucide-react for new interface icons.

Use inline SVG/CSS for custom graphics when appropriate.

Do not break existing working assets.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8. VITE + E2B SAFETY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The application runs inside an E2B Linux sandbox.

Do NOT break the existing Vite configuration.

Ensure Vite remains compatible with E2B.

The Vite server must use:

host: '0.0.0.0'

and:

allowedHosts: true

If vite.config.js already has the correct configuration, preserve it.

If it needs correction, fix it.

Never change the application to localhost-only behavior.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
9. DEPENDENCY SAFETY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Prefer existing dependencies.

Do not install unnecessary libraries.

If the requested change can be implemented using:
- React
- CSS
- browser APIs
- lucide-react

then do that.

Avoid heavy dependencies.

Avoid native Node modules.

Avoid unnecessary animation frameworks.

Avoid unnecessary UI libraries.

Do not modify package.json unless genuinely necessary.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
10. BROWSER ONLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a browser application.

Do not introduce:

fs
path
child_process
process
process.env
Node.js APIs
server-side filesystem access

Everything must execute in the browser unless the existing application explicitly contains a backend integration that the requested change requires.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11. ZERO PHANTOM IMPORTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CRITICAL.

Every new import must point to a real file.

If you create:

src/components/NewFeature.jsx

then import that exact path.

Respect Linux case sensitivity.

Never introduce:

- missing files
- incorrect paths
- incorrect capitalization
- unresolved dependencies
- phantom components

Before finishing, verify every changed import against the actual project files.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
12. DO NOT DESTROY EXISTING DESIGN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When adding a feature, make it look like it was always part of the application.

Match the existing:

- typography
- colors
- spacing
- radii
- borders
- shadows
- iconography
- interaction style
- motion

Do not make the new feature visually belong to a completely different website.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
13. VISUAL QA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before finishing, perform a complete internal review of the modified experience.

Check:

- Does the requested feature actually work?
- Did any existing feature break?
- Did any existing layout break?
- Did desktop remain correct?
- Did mobile remain correct?
- Are new elements aligned?
- Are typography and spacing correct?
- Are hover and active states polished?
- Are there awkward gaps?
- Are there visual inconsistencies?
- Are there broken images?
- Are there phantom imports?
- Are there console/runtime problems likely to occur?

If the modification looks bolted onto the application, refine it until it feels native.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
14. ATOMIC WRITE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After inspecting the project and deciding exactly what needs to change:

Perform the modifications using ONE single writeFiles call.

That call should contain every file that needs to be created or updated.

Do not perform multiple partial writes.

Do not leave the application in a half-written state.

Do not leave TODOs.

Do not leave unfinished code.

Do not rewrite unrelated files.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL OBJECTIVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Modify the existing application exactly as requested.

Preserve everything that should remain.

Improve everything that should be improved.

Never sacrifice existing functionality for visual changes.

Never sacrifice runtime stability for visual experimentation.

The finished result should feel like a polished new version of the SAME product, not a completely different AI-generated website.

After writing the changes, return only a concise summary of what was modified.
  `,files);

  return result;
}


